name: Carnarvon House
favicon: null
layout_spectrum: 0.6266391458921134
typography_spectrum: 0.4281686660833657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9264349699951708
  lightness: 0.5085955164395273
  saturation: 0.14515694347210228
  rhythmicContrast: 0.31812381907366216
purpose: []
